# Список всех объявлений
GET http://localhost:3000/api/offers HTTP/1.1

# # Полная информация определённого объявления
GET http://localhost:3000/api/offers/bQM-qQ HTTP/1.1

# # Список категорий
GET http://localhost:3000/api/category HTTP/1.1

# Создание нового объявления
POST http://localhost:3000/api/offers HTTP/1.1
Content-Type: application/json

{
  "category": ["Разное"],
  "description": "При покупке с меня бесплатная доставка в черте города. Две страницы заляпаны свежим кофе. Пользовались бережно и только по большим праздникам., Бонусом отдам все аксессуары.",
  "picture": "item03.jpg",
  "title": "Продам новую приставку Sony Playstation 5.",
  "type": "offer",
  "sum": 42698
}

# Обновление объявления
PUT http://localhost:3000/api/offers/bQM-qQ HTTP/1.1
Content-Type: application/json

{
  "category": ["Авто"],
  "description": "При покупке с меня бесплатная доставка в черте города. Две страницы заляпаны свежим кофе. Пользовались бережно и только по большим праздникам., Бонусом отдам все аксессуары.",
  "picture": "item03.jpg",
  "title": "Новый заголовок",
  "sum": 900,
  "type": "offer"
}

# Удаление объявления с идентификатором￼
DELETE http://localhost:3000/api/offers/bQM-qQ HTTP/1.1

# Список комментариев определённого объявления
GET http://localhost:3000/api/offers/bQM-qQ/comments HTTP/1.1

# Удаление из определённой публикации комментарий с идентификатором
DELETE http://localhost:3000/api/offers/bQM-qQ/comments/8y422F HTTP/1.1

# Добавление нового комментария к публикации
POST http://localhost:3000/api/offers/bQM-qQ/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Это новый комментарий"
}

# Возврат результатов поиска
GET http://localhost:3000/api/search?query=Куплю HTTP/1.1
